### ISSUE TITLE
BA-07 Crear servicio de obtencion de Roles

### ISSUE THREAD

**Issue by JHeisecke** [JHeisecke/project-traceability-backend#14]
Que envie una lista de objetos con [IdRol,NombreRol]

**Comment by jazvillagra** [comment]
Qué parámetros se le manda al endpoint? Solo el Id? Solo el nombre? o Ambos?

Este endpoint debe retornar un rolDTO? o solo el id y el nombre?

**Comment by JHeisecke** [comment]
1. En el formulario de creacion/edicion del usuario necesito todos los roles para asignar a un usuario, entonces creo que no iria ningun parametro en el endpoint.

2. Debe retornar una lista de RolDTO con id y nombre
