### ISSUE TITLE
BA-19 Insertar parametros de prioridad en base de datos

### ISSUE THREAD

**Issue by JHeisecke** [JHeisecke/project-traceability-backend#40]
Se debe insertar en Base de datos las distintas prioridades en la tabla de parametros

**Comment by jazvillagra** [comment]
@JHeisecke qué serían las prioridades?

**Comment by matias-fare-itti** [comment]
Valores para la tabla parámetros
* items, estados = [alto, medio, bajo]
* proyectos, estados = [en curso, en producción, analisis]
* fase, estados = [inicial,desarrollo, para revisión, completa]
* Linea Base, estados = [abierto, cerrado]

**Comment by jazvillagra** [comment]
@yedaloc cerrar si está terminado por favor
